// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart'
    show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_database/firebase_database.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

Future<void> initFirebase() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}

// final db = FirebaseFirestore.instance;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5PeMtq4kbgR1XfCGsxAvATvbeIPmzBv4',
    appId: '1:556179635448:web:c7d0324451a950b48e0f0d',
    messagingSenderId: '556179635448',
    projectId: 'aeroplane-58511',
    authDomain: 'aeroplane-58511.firebaseapp.com',
    storageBucket: 'aeroplane-58511.appspot.com',
    measurementId: 'G-2JJMCSL3H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD7ZKK9glGp09DMAIHLovVbBgfOAbJi7Y',
    appId: '1:556179635448:android:5ff192840939921f8e0f0d',
    messagingSenderId: '556179635448',
    projectId: 'aeroplane-58511',
    storageBucket: 'aeroplane-58511.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8UZbNeWHD-QsN-OAyY-iVOl3jIx5q1ZQ',
    appId: '1:556179635448:ios:e56386a501d798f38e0f0d',
    messagingSenderId: '556179635448',
    projectId: 'aeroplane-58511',
    storageBucket: 'aeroplane-58511.appspot.com',
    iosClientId:
        '556179635448-fnrn5ltrm0vfc0vo4d38o2e4dq6gbtab.apps.googleusercontent.com',
    iosBundleId: 'com.example.aeroplan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8UZbNeWHD-QsN-OAyY-iVOl3jIx5q1ZQ',
    appId: '1:556179635448:ios:e56386a501d798f38e0f0d',
    messagingSenderId: '556179635448',
    projectId: 'aeroplane-58511',
    storageBucket: 'aeroplane-58511.appspot.com',
    iosClientId:
        '556179635448-fnrn5ltrm0vfc0vo4d38o2e4dq6gbtab.apps.googleusercontent.com',
    iosBundleId: 'com.example.aeroplan',
  );
}
